---
title: "EU Population Over 65_SB"
author: "Raquel Baltazar - With Saghir's Updates"
date: "`r format(Sys.time(), '%a %d %b %Y (%H:%M:%S)')`"
output:
  html_document:
    theme: united
    highlight: tango
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

**We will use Eurostat indicator data for “Proportion of population aged 65 and over” to explore the geographical and time trends for the gender pay gap in the EU and compare Portugal with some European Union (EU) countries**

# Objective
The objective is to look at the geographical and time trends in the data. We will
answer the following questions:

+ What are the time trends for Portugal?
+ How does Portugal compare to other European countries?
+ Which countries have the largest and smallest population 65 and over in Europe over time?


# Understanding the Data

##  Proportion of population aged 65 and over

**% of total population who are aged 65 and over**

> The indicator measures the proportion (%) of the total population that is 65 years of age and older.

Taken from (https://ec.europa.eu/eurostat/databrowser/product/view/DEMO_PJANIND)

## Data Source 

The Eurostat proportion of population aged 65 and over data is based on data reported by the countries.

+ Eurostat Indicator code: TPS00028
The source dataset for TPS00028 is: DEMO_PJANIND
+ Source link: https://ec.europa.eu/eurostat/databrowser/view/tps00028/default/table?lang=en

The data is **Copyrighted** by Eurostat [Copyright/Licence Policy](http://ec.europa.eu/eurostat/statistics-explained/index.php/Copyright/licence_policy) is applicable.


